*&---------------------------------------------------------------------*
*& Report Zmilo_TEST_ERROR_080_099
*&---------------------------------------------------------------------*
*& Verifies the BLOCKED/ERROR classification for error codes 080-099.
*& The report does not change application data.
*&---------------------------------------------------------------------*
REPORT ZMILO_TEST_ERROR_080_099.

TYPES:
  BEGIN OF TY_CONTRACT,
    ERROR_CODE      TYPE ZMILO_ERROR_CODE,
    EXPECTED_STATUS TYPE STRING,
  END OF TY_CONTRACT.

TYPES TT_CONTRACT TYPE STANDARD TABLE OF TY_CONTRACT WITH EMPTY KEY.

START-OF-SELECTION.

  DATA LT_CONTRACT TYPE TT_CONTRACT.

  LT_CONTRACT = VALUE #(
    ( ERROR_CODE = 'QUERY_ID_INVALID' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'SAVED_QUERY_NOT_FOUND' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'SAVED_QUERY_INACTIVE' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'SAVED_QUERY_ACCESS_DENIED' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'SAVED_QUERY_NOT_OWNER' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'QUERY_NAME_REQUIRED' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'QUERY_VISIBILITY_INVALID' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'RESULT_ID_INVALID' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'RESULT_NOT_FOUND_OR_EXPIRED' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'RESULT_ACCESS_DENIED' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'DDIC_METADATA_NOT_FOUND' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'DDIC_FIELD_METADATA_NOT_FOUND' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'WHITELIST_PROFILE_NOT_FOUND' EXPECTED_STATUS = 'ERROR' )
    ( ERROR_CODE = 'MASK_PROFILE_NOT_FOUND' EXPECTED_STATUS = 'ERROR' )
    ( ERROR_CODE = 'MASK_RULE_INVALID' EXPECTED_STATUS = 'ERROR' )
    ( ERROR_CODE = 'MAX_ROWS_CONFIG_INVALID' EXPECTED_STATUS = 'ERROR' )
    ( ERROR_CODE = 'ROLE_CONFIG_AMBIGUOUS' EXPECTED_STATUS = 'ERROR' )
    ( ERROR_CODE = 'RESULT_CONFIG_INVALID' EXPECTED_STATUS = 'ERROR' )
    ( ERROR_CODE = 'UNSUPPORTED_DDIC_OBJECT_TYPE' EXPECTED_STATUS = 'BLOCKED' )
    ( ERROR_CODE = 'CONFIGURATION_ERROR' EXPECTED_STATUS = 'ERROR' ) ).

  WRITE: / '--- ERROR CONTRACT 080-099 ---'.

  LOOP AT LT_CONTRACT INTO DATA(LS_CONTRACT).
    DATA LX_VALIDATION TYPE REF TO ZCX_MILO_VALIDATION.

    CLEAR LX_VALIDATION.
    CASE LS_CONTRACT-ERROR_CODE.
      WHEN 'QUERY_ID_INVALID'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>QUERY_ID_INVALID ).
      WHEN 'SAVED_QUERY_NOT_FOUND'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>SAVED_QUERY_NOT_FOUND ).
      WHEN 'SAVED_QUERY_INACTIVE'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>SAVED_QUERY_INACTIVE ).
      WHEN 'SAVED_QUERY_ACCESS_DENIED'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>SAVED_QUERY_ACCESS_DENIED ).
      WHEN 'SAVED_QUERY_NOT_OWNER'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>SAVED_QUERY_NOT_OWNER ).
      WHEN 'QUERY_NAME_REQUIRED'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>QUERY_NAME_REQUIRED ).
      WHEN 'QUERY_VISIBILITY_INVALID'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>QUERY_VISIBILITY_INVALID ).
      WHEN 'RESULT_ID_INVALID'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>RESULT_ID_INVALID ).
      WHEN 'RESULT_NOT_FOUND_OR_EXPIRED'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>RESULT_NOT_FOUND_OR_EXPIRED ).
      WHEN 'RESULT_ACCESS_DENIED'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>RESULT_ACCESS_DENIED ).
      WHEN 'DDIC_METADATA_NOT_FOUND'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>DDIC_METADATA_NOT_FOUND ).
      WHEN 'DDIC_FIELD_METADATA_NOT_FOUND'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>DDIC_FIELD_METADATA_NOT_FOUND ).
      WHEN 'WHITELIST_PROFILE_NOT_FOUND'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>WHITELIST_PROFILE_NOT_FOUND ).
      WHEN 'MASK_PROFILE_NOT_FOUND'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>MASK_PROFILE_NOT_FOUND ).
      WHEN 'MASK_RULE_INVALID'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>MASK_RULE_INVALID ).
      WHEN 'MAX_ROWS_CONFIG_INVALID'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>MAX_ROWS_CONFIG_INVALID ).
      WHEN 'ROLE_CONFIG_AMBIGUOUS'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>ROLE_CONFIG_AMBIGUOUS ).
      WHEN 'RESULT_CONFIG_INVALID'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>RESULT_CONFIG_INVALID ).
      WHEN 'UNSUPPORTED_DDIC_OBJECT_TYPE'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>UNSUPPORTED_DDIC_OBJECT_TYPE ).
      WHEN 'CONFIGURATION_ERROR'.
        LX_VALIDATION = NEW #( TEXTID = ZCX_MILO_VALIDATION=>CONFIGURATION_ERROR ).
    ENDCASE.

    DATA(LV_MAPPED_CODE) =
      ZCL_MILO_SERVICE=>GET_VALIDATION_ERROR_CODE( LX_VALIDATION ).
    DATA(LV_TECHNICAL) =
      ZCL_MILO_ERROR_MAPPER=>IS_TECHNICAL_ERROR_CODE(
        LS_CONTRACT-ERROR_CODE ).
    DATA(LV_ACTUAL_STATUS) = COND STRING(
      WHEN LV_TECHNICAL = ABAP_TRUE THEN 'ERROR'
      ELSE 'BLOCKED' ).

    WRITE: / 'CODE:', LS_CONTRACT-ERROR_CODE.
    WRITE: / 'MAPPED:', LV_MAPPED_CODE.
    WRITE: / 'EXPECTED:', LS_CONTRACT-EXPECTED_STATUS.
    WRITE: / 'ACTUAL:', LV_ACTUAL_STATUS.

    IF LV_ACTUAL_STATUS = LS_CONTRACT-EXPECTED_STATUS
       AND LV_MAPPED_CODE = LS_CONTRACT-ERROR_CODE.
      WRITE: / 'RESULT: PASSED'.
    ELSE.
      WRITE: / 'RESULT: FAILED'.
    ENDIF.

    ULINE.
  ENDLOOP.
