*&---------------------------------------------------------------------*
*& Report ZMILO_TEST_WHERE_DEBUG
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZMILO_TEST_WHERE_DEBUG.

PARAMETERS P_WLIST TYPE ZMILO_WLIST_PROFILE_ID DEFAULT 'DEV_SAFE'.
PARAMETERS P_SQL   TYPE STRING LOWER CASE DEFAULT 'SELECT CARRID, CONNID FROM SPFLI WHERE CONNID BETWEEN 10 AND 100'.

DATA LV_SQL TYPE STRING.
DATA LV_WHERE_BY_VALIDATOR_REGEX TYPE STRING.
DATA LV_WHERE TYPE STRING.
DATA LV_OBJECT_NAME TYPE ZMILO_OBJ_NAME.
DATA LS_PARTS TYPE ZCL_MILO_SQL_PARSER=>TY_QUERY_PARTS.
DATA LX_VALIDATION TYPE REF TO ZCX_MILO_VALIDATION.

DATA LT_TOKEN TYPE STANDARD TABLE OF STRING WITH EMPTY KEY.
DATA LV_TOKEN TYPE STRING.
DATA LV_TOKEN_UPPER TYPE STRING.
DATA LV_CURRENT TYPE STRING.
DATA LV_WAIT_BETWEEN_AND TYPE ABAP_BOOL.
DATA LT_CONDITION TYPE STANDARD TABLE OF STRING WITH EMPTY KEY.
DATA LV_CONDITION TYPE STRING.
DATA LT_BETWEEN_TOKEN TYPE STANDARD TABLE OF STRING WITH EMPTY KEY.

START-OF-SELECTION.

  LV_SQL = P_SQL.

  REPLACE ALL OCCURRENCES OF CL_ABAP_CHAR_UTILITIES=>NEWLINE IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '\r\n' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '\n' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '\r' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '%0D%0A' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '%0d%0a' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '%0A' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '%0a' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '%0D' IN LV_SQL WITH SPACE.
  REPLACE ALL OCCURRENCES OF '%0d' IN LV_SQL WITH SPACE.

  LV_SQL = CONDENSE( LV_SQL ).
  LV_SQL = TO_UPPER( LV_SQL ).

  WRITE: / '--- INPUT ---'.
  WRITE: / 'WLIST:', P_WLIST.
  WRITE: / 'SQL_NORMALIZED:', LV_SQL.

  WRITE: /.
  WRITE: / '--- PARSER RESULT ---'.

  TRY.
      LS_PARTS = ZCL_MILO_SQL_PARSER=>PARSE( LV_SQL ).
      WRITE: / 'TABLE_NAME:', LS_PARTS-TABLE_NAME.
      WRITE: / 'IS_JOIN:', LS_PARTS-IS_JOIN.
      WRITE: / 'COLUMNS:', LS_PARTS-COLUMNS.
      WRITE: / 'FROM_SQL:', LS_PARTS-FROM_SQL.
      WRITE: / 'WHERE_SQL:', LS_PARTS-WHERE_SQL.
      WRITE: / 'ORDER_SQL:', LS_PARTS-ORDER_SQL.
    CATCH ZCX_MILO_VALIDATION INTO LX_VALIDATION.
      WRITE: / 'PARSER_ERROR:', LX_VALIDATION->GET_TEXT( ).
  ENDTRY.

  WRITE: /.
  WRITE: / '--- VALIDATOR WHERE REGEX RESULT ---'.

  FIND PCRE '\sWHERE\s+(.+?)(\sGROUP\s+BY\s+|\sHAVING\s+|\sORDER\s+BY\s+|$)'
    IN LV_SQL
    SUBMATCHES LV_WHERE_BY_VALIDATOR_REGEX.

  IF SY-SUBRC = 0.
    LV_WHERE_BY_VALIDATOR_REGEX = CONDENSE( LV_WHERE_BY_VALIDATOR_REGEX ).
    WRITE: / 'WHERE_BY_VALIDATOR_REGEX:', LV_WHERE_BY_VALIDATOR_REGEX.
  ELSE.
    WRITE: / 'WHERE_BY_VALIDATOR_REGEX: <NOT FOUND>'.
  ENDIF.

  LV_WHERE = LS_PARTS-WHERE_SQL.
  IF LV_WHERE IS INITIAL.
    LV_WHERE = LV_WHERE_BY_VALIDATOR_REGEX.
  ENDIF.

  WRITE: /.
  WRITE: / '--- CONDITION SPLIT DEBUG ---'.
  WRITE: / 'WHERE_USED:', LV_WHERE.

  IF LV_WHERE IS INITIAL.
    WRITE: / 'NO WHERE TO SPLIT'.
  ELSE.

    SPLIT LV_WHERE AT SPACE INTO TABLE LT_TOKEN.

    LOOP AT LT_TOKEN INTO LV_TOKEN.

      IF LV_TOKEN IS INITIAL.
        CONTINUE.
      ENDIF.

      LV_TOKEN_UPPER = TO_UPPER( LV_TOKEN ).
      WRITE: / 'TOKEN:', LV_TOKEN, 'UPPER:', LV_TOKEN_UPPER, 'WAIT_BETWEEN_AND:', LV_WAIT_BETWEEN_AND.

      IF LV_TOKEN_UPPER = 'AND'.

        IF LV_WAIT_BETWEEN_AND = ABAP_TRUE.
          IF LV_CURRENT IS INITIAL.
            LV_CURRENT = LV_TOKEN.
          ELSE.
            LV_CURRENT = |{ LV_CURRENT } { LV_TOKEN }|.
          ENDIF.
          LV_WAIT_BETWEEN_AND = ABAP_FALSE.
          CONTINUE.
        ENDIF.

        IF LV_CURRENT IS INITIAL.
          WRITE: / 'SPLIT_ERROR: AND found while current condition is empty'.
        ELSE.
          APPEND LV_CURRENT TO LT_CONDITION.
          WRITE: / 'APPEND_CONDITION:', LV_CURRENT.
        ENDIF.

        CLEAR LV_CURRENT.
        CONTINUE.

      ENDIF.

      IF LV_CURRENT IS INITIAL.
        LV_CURRENT = LV_TOKEN.
      ELSE.
        LV_CURRENT = |{ LV_CURRENT } { LV_TOKEN }|.
      ENDIF.

      IF LV_TOKEN_UPPER = 'BETWEEN'.
        LV_WAIT_BETWEEN_AND = ABAP_TRUE.
      ENDIF.

    ENDLOOP.

    IF LV_WAIT_BETWEEN_AND = ABAP_TRUE.
      WRITE: / 'SPLIT_ERROR: BETWEEN found but matching AND was not found'.
    ENDIF.

    IF LV_CURRENT IS INITIAL.
      WRITE: / 'SPLIT_ERROR: LAST CONDITION IS EMPTY'.
    ELSE.
      APPEND LV_CURRENT TO LT_CONDITION.
      WRITE: / 'APPEND_CONDITION:', LV_CURRENT.
    ENDIF.

    WRITE: /.
    WRITE: / '--- BETWEEN TOKEN DEBUG ---'.

    LOOP AT LT_CONDITION INTO LV_CONDITION.
      CLEAR LT_BETWEEN_TOKEN.
      LV_CONDITION = CONDENSE( LV_CONDITION ).
      SPLIT LV_CONDITION AT SPACE INTO TABLE LT_BETWEEN_TOKEN.

      WRITE: / 'CONDITION:', LV_CONDITION.
      WRITE: / 'TOKEN_COUNT:', LINES( LT_BETWEEN_TOKEN ).

      DO LINES( LT_BETWEEN_TOKEN ) TIMES.
        READ TABLE LT_BETWEEN_TOKEN INTO LV_TOKEN INDEX SY-INDEX.
        WRITE: / '  IDX:', SY-INDEX, 'TOKEN:', LV_TOKEN.
      ENDDO.
    ENDLOOP.

  ENDIF.

  WRITE: /.
  WRITE: / '--- REAL VALIDATOR RESULT ---'.

  TRY.
      ZCL_MILO_VALIDATOR=>VALIDATE_SELECT_SQL(
        EXPORTING
          IV_SQL              = P_SQL
          IV_WLIST_PROFILE_ID = P_WLIST
        IMPORTING
          EV_OBJECT_NAME      = LV_OBJECT_NAME ).

      WRITE: / 'VALIDATOR_STATUS: PASS'.
      WRITE: / 'OBJECT_NAME:', LV_OBJECT_NAME.

    CATCH ZCX_MILO_VALIDATION INTO LX_VALIDATION.
      WRITE: / 'VALIDATOR_STATUS: BLOCKED'.
      WRITE: / 'VALIDATOR_ERROR:', LX_VALIDATION->GET_TEXT( ).
  ENDTRY.
