*&---------------------------------------------------------------------*
*& Report Zmilo_TEST_TECH_ERROR_CONTRACT
*&---------------------------------------------------------------------*
*& Verifies the Phase 3 technical error classification without changing
*& result or saved-query persistence data.
*&---------------------------------------------------------------------*
REPORT ZMILO_TEST_TECH_ERROR_CONTRACT.

TYPES TT_ERROR_CODE TYPE STANDARD TABLE OF ZMILO_ERROR_CODE
  WITH EMPTY KEY.

START-OF-SELECTION.

  DATA LT_ERROR_CODE TYPE TT_ERROR_CODE.

  APPEND 'QUERY_EXECUTION_FAILED' TO LT_ERROR_CODE.
  APPEND 'DYNAMIC_SQL_SYNTAX_ERROR' TO LT_ERROR_CODE.
  APPEND 'DATA_TYPE_MISMATCH' TO LT_ERROR_CODE.
  APPEND 'NUMERIC_OVERFLOW' TO LT_ERROR_CODE.
  APPEND 'RESULT_SERIALIZATION_FAILED' TO LT_ERROR_CODE.
  APPEND 'RESULT_STORAGE_FAILED' TO LT_ERROR_CODE.
  APPEND 'QUERY_STORAGE_FAILED' TO LT_ERROR_CODE.
  APPEND 'LOG_WRITE_FAILED' TO LT_ERROR_CODE.
  APPEND 'UUID_GENERATION_FAILED' TO LT_ERROR_CODE.
  APPEND 'INTERNAL_ERROR' TO LT_ERROR_CODE.

  WRITE: / '--- TECHNICAL ERROR CONTRACT ---'.

  LOOP AT LT_ERROR_CODE INTO DATA(LV_ERROR_CODE).
    DATA(LV_TECHNICAL) =
      ZCL_MILO_ERROR_MAPPER=>IS_TECHNICAL_ERROR_CODE( LV_ERROR_CODE ).
    DATA(LV_ERROR_TEXT) =
      ZCL_MILO_ERROR_MAPPER=>GET_SAFE_TECHNICAL_TEXT( LV_ERROR_CODE ).
    DATA LV_STATUS TYPE STRING.

    IF LV_TECHNICAL = ABAP_TRUE.
      LV_STATUS = 'ERROR'.
    ELSE.
      LV_STATUS = 'FAILED CLASSIFICATION'.
    ENDIF.

    WRITE: / 'CODE:', LV_ERROR_CODE.
    WRITE: / 'STATUS:', LV_STATUS.
    WRITE: / 'TEXT:', LV_ERROR_TEXT.
    ULINE.
  ENDLOOP.

  DATA(LV_VALIDATION_IS_TECHNICAL) =
    ZCL_MILO_ERROR_MAPPER=>IS_TECHNICAL_ERROR_CODE( 'EMPTY_SQL' ).

  WRITE: / '--- VALIDATION REGRESSION ---'.
  WRITE: / 'CODE: EMPTY_SQL'.
  WRITE: / 'EXPECTED STATUS: BLOCKED'.
  WRITE: / 'TECHNICAL:', LV_VALIDATION_IS_TECHNICAL.

  IF LV_VALIDATION_IS_TECHNICAL = ABAP_FALSE.
    WRITE: / 'RESULT: PASSED'.
  ELSE.
    WRITE: / 'RESULT: FAILED'.
  ENDIF.
