REPORT ZMILO_TEST_PFCG_ROLE.

PARAMETERS P_PROF TYPE ZMILO_PROFILE_ID DEFAULT 'DEV'.

START-OF-SELECTION.

  DATA LS_ROLE       TYPE ZMILO_ROLE.
  DATA LT_ASSIGNMENT TYPE STANDARD TABLE OF AGR_USERS WITH EMPTY KEY.
  DATA LT_PARENT     TYPE STANDARD TABLE OF AGR_AGRS WITH EMPTY KEY.
  DATA LT_PARENT_USR TYPE STANDARD TABLE OF AGR_USERS WITH EMPTY KEY.
  DATA LV_REQUIRED_ROLE TYPE AGR_USERS-AGR_NAME.
  DATA LV_DEFINED_ROLE  TYPE AGR_DEFINE-AGR_NAME.
  DATA LV_ASSIGNED_ROLE TYPE AGR_USERS-AGR_NAME.
  DATA LV_EXPECTED_CODE TYPE ZMILO_ERROR_CODE.

  WRITE: / 'CURRENT USER:', SY-UNAME,
         / 'CURRENT CLIENT:', SY-MANDT,
         / 'PROFILE:', P_PROF.
  ULINE.

  SELECT SINGLE *
    FROM ZMILO_ROLE
    WHERE PROFILE_ID = @P_PROF
    INTO @LS_ROLE.

  IF SY-SUBRC <> 0.
    WRITE: / 'PROFILE CONFIG: NOT FOUND'.
    RETURN.
  ENDIF.

  WRITE: / 'CONFIGURED PFCG ROLE:', LS_ROLE-PFCG_ROLE,
         / 'PROFILE ACTIVE:', LS_ROLE-IS_ACTIVE.
  ULINE.

  LV_REQUIRED_ROLE = TO_UPPER( CONDENSE( LS_ROLE-PFCG_ROLE ) ).

  WRITE: / '--- SERVICE CHECK EMULATION ---'.

  IF LS_ROLE-IS_ACTIVE <> ABAP_TRUE.
    LV_EXPECTED_CODE = 'PROFILE_INACTIVE'.
    WRITE: / 'STEP PROFILE ACTIVE: FAILED'.
  ELSE.
    WRITE: / 'STEP PROFILE ACTIVE: PASSED'.
  ENDIF.

  IF LV_EXPECTED_CODE IS INITIAL.
    IF LV_REQUIRED_ROLE IS INITIAL.
      LV_EXPECTED_CODE = 'PFCG_ROLE_NOT_CONFIGURED'.
      WRITE: / 'STEP PFCG ROLE CONFIGURED: FAILED'.
    ELSE.
      WRITE: / 'STEP PFCG ROLE CONFIGURED: PASSED',
             / 'NORMALIZED PFCG ROLE:', LV_REQUIRED_ROLE.
    ENDIF.
  ENDIF.

  IF LV_EXPECTED_CODE IS INITIAL.
    SELECT SINGLE AGR_NAME
      FROM AGR_DEFINE
      WHERE AGR_NAME = @LV_REQUIRED_ROLE
      INTO @LV_DEFINED_ROLE
      BYPASSING BUFFER.

    IF SY-SUBRC <> 0.
      LV_EXPECTED_CODE = 'PFCG_ROLE_NOT_CONFIGURED'.
      WRITE: / 'STEP ROLE EXISTS IN AGR_DEFINE: FAILED'.
    ELSE.
      WRITE: / 'STEP ROLE EXISTS IN AGR_DEFINE: PASSED'.
    ENDIF.
  ENDIF.

  IF LV_EXPECTED_CODE IS INITIAL.
    SELECT SINGLE AGR_NAME
      FROM AGR_USERS
      WHERE UNAME    = @SY-UNAME
        AND AGR_NAME = @LV_REQUIRED_ROLE
        AND FROM_DAT <= @SY-DATUM
        AND TO_DAT   >= @SY-DATUM
      INTO @LV_ASSIGNED_ROLE
      BYPASSING BUFFER.

    IF SY-SUBRC <> 0.
      LV_EXPECTED_CODE = 'USER_ROLE_MISSING'.
      WRITE: / 'STEP VALID USER ASSIGNMENT: FAILED'.
    ELSE.
      WRITE: / 'STEP VALID USER ASSIGNMENT: PASSED'.
    ENDIF.
  ENDIF.

  IF LV_EXPECTED_CODE IS INITIAL.
    WRITE: / 'EXPECTED AUTHORIZATION RESULT: ALLOWED'.
  ELSE.
    WRITE: / 'EXPECTED AUTHORIZATION RESULT: BLOCKED',
           / 'EXPECTED ERROR CODE:', LV_EXPECTED_CODE.
  ENDIF.

  ULINE.

  SELECT *
    FROM AGR_USERS
    WHERE UNAME    = @SY-UNAME
      AND AGR_NAME = @LS_ROLE-PFCG_ROLE
    ORDER BY FROM_DAT, TO_DAT
    INTO TABLE @LT_ASSIGNMENT
    BYPASSING BUFFER.

  IF LT_ASSIGNMENT IS INITIAL.
    WRITE: / 'AGR_USERS EXACT MATCH: NONE'.
  ELSE.
    WRITE: / 'AGR_USERS EXACT MATCH:'.

    LOOP AT LT_ASSIGNMENT INTO DATA(LS_ASSIGNMENT).
      WRITE: / 'ROLE:', LS_ASSIGNMENT-AGR_NAME,
             / 'VALID FROM:', LS_ASSIGNMENT-FROM_DAT,
             / 'VALID TO:', LS_ASSIGNMENT-TO_DAT,
             / 'VALID TODAY:',
               XSDBOOL( LS_ASSIGNMENT-FROM_DAT <= SY-DATUM
                    AND LS_ASSIGNMENT-TO_DAT >= SY-DATUM ),
             / 'FROM COMPOSITE:', LS_ASSIGNMENT-COL_FLAG,
             / 'FROM HR ORG:', LS_ASSIGNMENT-ORG_FLAG,
             / 'EXCLUDE FLAG:', LS_ASSIGNMENT-EXCLUDE.
      ULINE.
    ENDLOOP.
  ENDIF.

  SELECT *
    FROM AGR_AGRS
    WHERE CHILD_AGR = @LS_ROLE-PFCG_ROLE
    ORDER BY AGR_NAME
    INTO TABLE @LT_PARENT
    BYPASSING BUFFER.

  IF LT_PARENT IS INITIAL.
    WRITE: / 'COMPOSITE PARENT ROLE: NONE'.
  ELSE.
    WRITE: / 'COMPOSITE PARENT ROLES:'.

    LOOP AT LT_PARENT INTO DATA(LS_PARENT).
      WRITE: / LS_PARENT-AGR_NAME.
    ENDLOOP.
  ENDIF.

  IF LT_PARENT IS NOT INITIAL.
    SELECT *
      FROM AGR_USERS
      FOR ALL ENTRIES IN @LT_PARENT
      WHERE UNAME    = @SY-UNAME
        AND AGR_NAME = @LT_PARENT-AGR_NAME
      ORDER BY PRIMARY KEY
      INTO TABLE @LT_PARENT_USR
      BYPASSING BUFFER.

    IF LT_PARENT_USR IS INITIAL.
      WRITE: / 'USER COMPOSITE ASSIGNMENT: NONE'.
    ELSE.
      WRITE: / 'USER COMPOSITE ASSIGNMENTS:'.

      LOOP AT LT_PARENT_USR INTO DATA(LS_PARENT_USR).
        WRITE: / 'ROLE:', LS_PARENT_USR-AGR_NAME,
               / 'VALID FROM:', LS_PARENT_USR-FROM_DAT,
               / 'VALID TO:', LS_PARENT_USR-TO_DAT,
               / 'VALID TODAY:',
                 XSDBOOL( LS_PARENT_USR-FROM_DAT <= SY-DATUM
                      AND LS_PARENT_USR-TO_DAT >= SY-DATUM ).
        ULINE.
      ENDLOOP.
    ENDIF.
  ENDIF.

  TRY.
      DATA(LS_SERVICE_ROLE) =
        ZCL_MILO_SERVICE=>GET_ROLE_PROFILE( P_PROF ).

      WRITE: / 'SERVICE AUTHORIZATION RESULT: ALLOWED',
             / 'SERVICE PROFILE:', LS_SERVICE_ROLE-PROFILE_ID,
             / 'SERVICE PFCG ROLE:', LS_SERVICE_ROLE-PFCG_ROLE.

    CATCH ZCX_MILO_VALIDATION INTO DATA(LX_VALIDATION).
      WRITE: / 'SERVICE AUTHORIZATION RESULT: BLOCKED',
             / 'ERROR CODE:',
               ZCL_MILO_SERVICE=>GET_VALIDATION_ERROR_CODE(
                 LX_VALIDATION ),
             / 'ERROR TEXT:', LX_VALIDATION->GET_TEXT( ).
  ENDTRY.
