*&---------------------------------------------------------------------*
*& Report Zmilo_TEST_AGGREGATE
*&---------------------------------------------------------------------*
REPORT ZMILO_TEST_AGGREGATE.

PARAMETERS P_PROF TYPE ZMILO_PROFILE_ID DEFAULT 'DEV'.
PARAMETERS P_SQL  TYPE STRING LOWER CASE
  DEFAULT 'SELECT CARRID, MIN(DISTANCE) AS MIN_DISTANCE, MAX(DISTANCE) AS MAX_DISTANCE FROM SPFLI GROUP BY CARRID ORDER BY CARRID'.

START-OF-SELECTION.

  DATA LS_ROLE      TYPE ZMILO_ROLE.
  DATA LV_OBJ       TYPE ZMILO_OBJ_NAME.
  DATA LV_COUNT     TYPE I.
  DATA LV_RETURNED  TYPE I.
  DATA LV_STATUS    TYPE STRING.
  DATA LV_MAX_ROWS  TYPE I.
  DATA LV_TRUNCATED TYPE ABAP_BOOL.
  DATA LV_JSON      TYPE STRING.
  DATA LV_ERROR_CODE TYPE ZMILO_ERROR_CODE.
  DATA LV_ERROR_TEXT TYPE STRING.

  LS_ROLE = ZCL_MILO_CONFIG=>GET_ROLE_CONFIG( P_PROF ).

  WRITE: / 'PROFILE:', P_PROF.
  WRITE: / 'WLIST:', LS_ROLE-WLIST_PROFILE_ID.

  TRY.
      DATA(LS_PARTS) = ZCL_MILO_SQL_PARSER=>PARSE( P_SQL ).

      WRITE: / 'PARSE: SUCCESS'.
      WRITE: / 'SELECT INPUT:', LS_PARTS-COLUMNS.
      WRITE: / 'GROUP:', LS_PARTS-GROUP_SQL.
      WRITE: / 'HAVING RAW:', LS_PARTS-HAVING_SQL.
      WRITE: / 'HAVING NORMALIZED:',
        ZCL_MILO_SQL_PARSER=>NORMALIZE_COUNT_DISTINCT_SQL(
          LS_PARTS-HAVING_SQL ).

      LOOP AT LS_PARTS-FIELDS INTO DATA(LS_FIELD).
        WRITE: / 'FIELD:', LS_FIELD-FIELD_NAME,
                 'FUNCTION:', LS_FIELD-AGG_FUNC,
                 'DISTINCT:', LS_FIELD-IS_DISTINCT,
                 'OUTPUT:', LS_FIELD-OUTPUT_KEY.
      ENDLOOP.

    CATCH ZCX_MILO_VALIDATION INTO DATA(LX_PARSE).
      WRITE: / 'PARSE: BLOCKED'.
      WRITE: / 'ERROR:', LX_PARSE->GET_TEXT( ).
      RETURN.
  ENDTRY.

  TRY.
      ZCL_MILO_EXECUTOR=>EXECUTE_SELECT(
        EXPORTING
          IV_SQL              = P_SQL
          IV_WLIST_PROFILE_ID = LS_ROLE-WLIST_PROFILE_ID
          IV_MASK_PROFILE_ID  = LS_ROLE-MASK_PROFILE_ID
        IMPORTING
          EV_OBJECT_NAME      = LV_OBJ
          EV_ROW_COUNT        = LV_COUNT
          EV_RETURNED_ROWS    = LV_RETURNED
          EV_STATUS           = LV_STATUS
          EV_MAX_ROWS         = LV_MAX_ROWS
          EV_TRUNCATED        = LV_TRUNCATED
          EV_ROWS_JSON        = LV_JSON
          EV_ERROR_CODE       = LV_ERROR_CODE
          EV_ERROR_TEXT       = LV_ERROR_TEXT ).

      WRITE: / 'EXECUTOR STATUS:', LV_STATUS.
      WRITE: / 'OBJECT:', LV_OBJ.
      WRITE: / 'ROWS:', LV_COUNT.

      IF LV_STATUS <> 'SUCCESS'.
        WRITE: / 'EXECUTOR ERROR CODE:', LV_ERROR_CODE.
        WRITE: / 'EXECUTOR ERROR:', LV_ERROR_TEXT.
        RETURN.
      ENDIF.

    CATCH ZCX_MILO_VALIDATION INTO DATA(LX_VALIDATION).
      WRITE: / 'EXECUTOR: BLOCKED'.
      WRITE: / 'ERROR:', LX_VALIDATION->GET_TEXT( ).
      RETURN.
    CATCH CX_ROOT INTO DATA(LX_EXECUTOR).
      WRITE: / 'EXECUTOR: TECHNICAL ERROR'.
      WRITE: / 'ERROR:', LX_EXECUTOR->GET_TEXT( ).
      RETURN.
  ENDTRY.

  TRY.
      DATA(LS_SERVICE_RESULT) = ZCL_MILO_SERVICE=>RUN_QUERY_RESULT(
        IV_PROFILE_ID = P_PROF
        IV_SQL        = P_SQL
        IV_PAGE       = 1 ).

      WRITE: / 'SERVICE STATUS:', LS_SERVICE_RESULT-STATUS.
      WRITE: / 'SERVICE ERROR CODE:', LS_SERVICE_RESULT-ERROR_CODE.

      IF LS_SERVICE_RESULT-ERROR_TEXT IS NOT INITIAL.
        WRITE: / 'SERVICE ERROR:', LS_SERVICE_RESULT-ERROR_TEXT.
      ENDIF.

      IF LS_SERVICE_RESULT-STATUS <> 'SUCCESS'.
        RETURN.
      ENDIF.

    CATCH CX_ROOT INTO DATA(LX_SERVICE).
      WRITE: / 'SERVICE: TECHNICAL ERROR'.
      WRITE: / 'ERROR:', LX_SERVICE->GET_TEXT( ).
      RETURN.
  ENDTRY.

  TRY.
      DATA(LT_COLUMN) = ZCL_MILO_SERVICE=>BUILD_RESULT_COLUMNS(
        IV_PROFILE_ID = P_PROF
        IV_SQL        = P_SQL ).

      WRITE: / 'COLUMN METADATA: SUCCESS'.
      WRITE: / 'COLUMN COUNT:', LINES( LT_COLUMN ).

      LOOP AT LT_COLUMN INTO DATA(LS_COLUMN).
        WRITE: / 'POSITION:', LS_COLUMN-COLUMN_POSITION,
                 'COLUMN:', LS_COLUMN-FIELD_NAME,
                 'TYPE:', LS_COLUMN-ABAP_TYPE,
                 'LENGTH:', LS_COLUMN-LENGTH,
                 'DECIMALS:', LS_COLUMN-DECIMALS.
      ENDLOOP.

    CATCH ZCX_MILO_VALIDATION INTO DATA(LX_COLUMN_VALIDATION).
      WRITE: / 'COLUMN METADATA: BLOCKED'.
      WRITE: / 'ERROR:', LX_COLUMN_VALIDATION->GET_TEXT( ).
    CATCH CX_ROOT INTO DATA(LX_COLUMN).
      WRITE: / 'COLUMN METADATA: TECHNICAL ERROR'.
      WRITE: / 'ERROR:', LX_COLUMN->GET_TEXT( ).
  ENDTRY.
