PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMILO_ROLE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMILO_ROLE-PROFILE_ID .
    FIELD ZMILO_ROLE-PFCG_ROLE .
    FIELD ZMILO_ROLE-MAX_ROWS .
    FIELD ZMILO_ROLE-WLIST_PROFILE_ID .
    FIELD ZMILO_ROLE-MASK_PROFILE_ID .
    FIELD ZMILO_ROLE-DESCRIPTION .
    FIELD ZMILO_ROLE-CREATED_DATE .
    FIELD ZMILO_ROLE-IS_ACTIVE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMILO_ROLE-PROFILE_ID .
    FIELD ZMILO_ROLE-PFCG_ROLE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
