PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMILO_MASK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMILO_MASK-MASK_PROFILE_ID .
    FIELD ZMILO_MASK-OBJ_NAME .
    FIELD ZMILO_MASK-FIELD_NAME .
    FIELD ZMILO_MASK-MASK_TYPE .
    FIELD ZMILO_MASK-IS_ACTIVE .
    FIELD ZMILO_MASK-DESCRIPTION .
    FIELD ZMILO_MASK-CREATED_DATE .
    FIELD ZMILO_MASK-MASK_VALUE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMILO_MASK-MASK_PROFILE_ID .
    FIELD ZMILO_MASK-OBJ_NAME .
    FIELD ZMILO_MASK-FIELD_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
