PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMILO_WLIST CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMILO_WLIST-WLIST_PROFILE_ID .
    FIELD ZMILO_WLIST-OBJ_NAME .
    FIELD ZMILO_WLIST-OBJ_TYPE .
    FIELD ZMILO_WLIST-IS_ACTIVE .
    FIELD ZMILO_WLIST-MAX_ROWS .
    FIELD ZMILO_WLIST-DESCRIPTION .
    FIELD ZMILO_WLIST-CREATED_DATE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMILO_WLIST-WLIST_PROFILE_ID .
    FIELD ZMILO_WLIST-OBJ_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
